name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Install cs
      uses: coursier/cache-action@v6
      uses: VirtusLab/scala-cli-setup@main
    - name: Install scalafmt
      run: cs setup
    - name: Check formatting
      run: scalafmt --check
    - name: Build and Test
      run: sbt -v +test


